// Assembly pcapFileIO, Version 1.0.0.0

[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows = true)]
[assembly: System.Reflection.AssemblyConfiguration("")]
[assembly: System.Reflection.AssemblyCompany("Open Universiteit Nederland")]
[assembly: System.Reflection.AssemblyCopyright("Copyright P.J. Molijn 2014")]
[assembly: System.Reflection.AssemblyDescription("http://www.ou.nl/")]
[assembly: System.Reflection.AssemblyProduct("pcapFileIO")]
[assembly: System.Reflection.AssemblyTitle("pcapFileIO")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Runtime.InteropServices.Guid("78A875B2-2528-42DD-9832-44FB690396BE")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0.0")]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]